"""Add teams map stats table

Revision ID: 81c39e9e8ac6
Revises: 27ed4dd23ea9
Create Date: 2025-03-29 00:07:23.378512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c39e9e8ac6"
down_revision: Union[str, None] = "27ed4dd23ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_map_stats",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "map",
            sa.Enum(
                "Anubis",
                "Dust2",
                "Mirage",
                "Nuke",
                "Vertigo",
                "Ancient",
                "Inferno",
                "Train",
                name="mapname",
            ),
            nullable=False,
        ),
        sa.Column("matches_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column("matches_won", sa.Integer(), server_default="0", nullable=False),
        sa.Column("win_rate", sa.Float(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_map_stats")
    # ### end Alembic commands ###
