"""Add fields in tokens table

Revision ID: fa9c58e0a7eb
Revises: dba89c2a6c63
Create Date: 2025-02-02 16:36:19.168254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa9c58e0a7eb"
down_revision: Union[str, None] = "dba89c2a6c63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("device_id", sa.String(), nullable=True))
    op.add_column("tokens", sa.Column("expired_time", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "expired_time")
    op.drop_column("tokens", "device_id")
    # ### end Alembic commands ###
