"""Add column best_of

Revision ID: 2c410a0f465a
Revises: c01fb92bb140
Create Date: 2025-01-15 18:37:42.422536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c410a0f465a"
down_revision: Union[str, None] = "c01fb92bb140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("best_of", sa.Integer(), nullable=False))
    op.add_column("player_stats", sa.Column("round", sa.Integer(), nullable=False))
    op.add_column("player_stats", sa.Column("nickname", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_stats", "nickname")
    op.drop_column("player_stats", "round")
    op.drop_column("matches", "best_of")
    # ### end Alembic commands ###
