"""Create tokens table

Revision ID: dba89c2a6c63
Revises: fe4473925a62
Create Date: 2025-02-02 01:38:48.143574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dba89c2a6c63"
down_revision: Union[str, None] = "fe4473925a62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column(
            "revoked", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###
