"""Add fields for elo

Revision ID: 28bf4629ec22
Revises: 81c39e9e8ac6
Create Date: 2025-04-01 14:36:25.871337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28bf4629ec22"
down_revision: Union[str, None] = "81c39e9e8ac6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("faceit_elo", sa.Integer(), nullable=True))
    op.add_column("teams", sa.Column("average_faceit_elo", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "average_faceit_elo")
    op.drop_column("players", "faceit_elo")
    # ### end Alembic commands ###
