"""Add match info tables

Revision ID: 27ed4dd23ea9
Revises: 4c0b47674b8b
Create Date: 2025-03-28 00:52:11.667688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27ed4dd23ea9"
down_revision: Union[str, None] = "4c0b47674b8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_pick_ban_info",
        sa.Column(
            "map",
            sa.Enum(
                "Anubis",
                "Dust2",
                "Mirage",
                "Nuke",
                "Vertigo",
                "Ancient",
                "Inferno",
                "Train",
                name="mapname",
            ),
            nullable=False,
        ),
        sa.Column(
            "map_status",
            sa.Enum("Banned", "Picked", "Default", name="mapstatus"),
            nullable=False,
        ),
        sa.Column("initiator", sa.String(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "map_result_info",
        sa.Column(
            "map",
            sa.Enum(
                "Anubis",
                "Dust2",
                "Mirage",
                "Nuke",
                "Vertigo",
                "Ancient",
                "Inferno",
                "Train",
                name="mapname",
            ),
            nullable=False,
        ),
        sa.Column("first_team", sa.String(), nullable=False),
        sa.Column("second_team", sa.String(), nullable=False),
        sa.Column("first_half_score_first_team", sa.Integer(), nullable=False),
        sa.Column("second_half_score_first_team", sa.Integer(), nullable=False),
        sa.Column("overtime_score_first_team", sa.Integer(), nullable=False),
        sa.Column("total_score_first_team", sa.Integer(), nullable=False),
        sa.Column("first_half_score_second_team", sa.Integer(), nullable=False),
        sa.Column("second_half_score_second_team", sa.Integer(), nullable=False),
        sa.Column("overtime_score_second_team", sa.Integer(), nullable=False),
        sa.Column("total_score_second_team", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_result_info")
    op.drop_table("map_pick_ban_info")
    # ### end Alembic commands ###
