"""Add status of match

Revision ID: ea4c8abd0373
Revises: 4189707c05d9
Create Date: 2025-01-22 21:42:50.711375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea4c8abd0373"
down_revision: Union[str, None] = "4189707c05d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "IN_PROGRESS", "COMPLETED", name="matchstatus"),
            server_default="scheduled",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "status")
    # ### end Alembic commands ###
