"""Add field original sourse

Revision ID: c6aecb49c031
Revises: c099b13ae592
Create Date: 2025-04-08 01:39:32.838072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6aecb49c031'
down_revision: Union[str, None] = 'c099b13ae592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'matches',
        sa.Column('original_source', sa.String(), server_default='null', nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'original_source')
    # ### end Alembic commands ###
