"""Add match info tables

Revision ID: c48016527adf
Revises: 4c0b47674b8b
Create Date: 2025-03-27 20:40:10.849269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c48016527adf"
down_revision: Union[str, None] = "4c0b47674b8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_pick_ban_info",
        sa.Column(
            "map",
            sa.Enum(
                "ANUBIS",
                "DUST2",
                "MIRAGE",
                "NUKE",
                "VERTIGO",
                "ANCIENT",
                "INFERNO",
                "TRAIN",
                name="mapname",
            ),
            nullable=False,
        ),
        sa.Column(
            "map_status",
            sa.Enum("BANNED", "PICKED", "DEFAULT", name="mapstatus"),
            nullable=False,
        ),
        sa.Column("initiator", sa.String(length=50), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "map_result_info",
        sa.Column(
            "map",
            sa.Enum(
                "ANUBIS",
                "DUST2",
                "MIRAGE",
                "NUKE",
                "VERTIGO",
                "ANCIENT",
                "INFERNO",
                "TRAIN",
                name="mapname",
            ),
            nullable=False,
        ),
        sa.Column("first_team", sa.String(length=50), nullable=False),
        sa.Column("second_team", sa.String(length=50), nullable=False),
        sa.Column("first_half_score_first_team", sa.Integer(), nullable=False),
        sa.Column("second_half_score_first_team", sa.Integer(), nullable=False),
        sa.Column("first_half_score_second_team", sa.Integer(), nullable=False),
        sa.Column("second_half_score_second_team", sa.Integer(), nullable=False),
        sa.Column("total_score_first_team", sa.Integer(), nullable=False),
        sa.Column("total_score_second_team", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_result_info")
    op.drop_table("map_pick_ban_info")
    # ### end Alembic commands ###
