"""link player_stats, match, player

Revision ID: c01fb92bb140
Revises: c7dd83f232dd
Create Date: 2025-01-15 17:44:03.854944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c01fb92bb140"
down_revision: Union[str, None] = "c7dd83f232dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_match_association")
    op.drop_table("matches_info")
    op.create_table(
        "player_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("headshots_percentage", sa.Integer(), nullable=False),
        sa.Column("adr", sa.Float(), nullable=False),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("mvps", sa.Integer(), nullable=True),
        sa.Column("damage", sa.Integer(), nullable=True),
        sa.Column("headshots", sa.Integer(), nullable=True),
        sa.Column("kd", sa.Float(), nullable=True),
        sa.Column("kpr", sa.Float(), nullable=True),
        sa.Column("double", sa.Integer(), nullable=True),
        sa.Column("triple", sa.Integer(), nullable=True),
        sa.Column("quadro", sa.Integer(), nullable=True),
        sa.Column("penta", sa.Integer(), nullable=True),
        sa.Column("clutch_kills", sa.Integer(), nullable=True),
        sa.Column("count_1v1", sa.Integer(), nullable=True),
        sa.Column("count_1v2", sa.Integer(), nullable=True),
        sa.Column("wins_1v1", sa.Integer(), nullable=True),
        sa.Column("wins_1v2", sa.Integer(), nullable=True),
        sa.Column("match_1v1_win_rate", sa.Float(), nullable=True),
        sa.Column("match_1v2_win_rate", sa.Float(), nullable=True),
        sa.Column("first_kills", sa.Integer(), nullable=True),
        sa.Column("entry_count", sa.Integer(), nullable=True),
        sa.Column("entry_wins", sa.Integer(), nullable=True),
        sa.Column("match_entry_rate", sa.Float(), nullable=True),
        sa.Column("match_entry_success_rate", sa.Float(), nullable=True),
        sa.Column("sniper_kills", sa.Integer(), nullable=True),
        sa.Column("sniper_kill_rate_per_round", sa.Float(), nullable=True),
        sa.Column("sniper_kill_rate_per_match", sa.Float(), nullable=True),
        sa.Column("pistol_kills", sa.Float(), nullable=True),
        sa.Column("knife_kills", sa.Integer(), nullable=True),
        sa.Column("zeus_kills", sa.Float(), nullable=True),
        sa.Column("utility_count", sa.Integer(), nullable=True),
        sa.Column("utility_successes", sa.Integer(), nullable=True),
        sa.Column("utility_enemies", sa.Integer(), nullable=True),
        sa.Column("utility_damage", sa.Integer(), nullable=True),
        sa.Column("utility_usage_per_round", sa.Float(), nullable=True),
        sa.Column("utility_damage_success_rate_per_match", sa.Float(), nullable=True),
        sa.Column("utility_successes_rate_per_match", sa.Float(), nullable=True),
        sa.Column("utility_damage_per_round_in_a_match", sa.Float(), nullable=True),
        sa.Column("flash_count", sa.Integer(), nullable=True),
        sa.Column("enemies_flashed", sa.Integer(), nullable=True),
        sa.Column("flash_successes", sa.Integer(), nullable=True),
        sa.Column("flashes_per_round_in_a_match", sa.Float(), nullable=True),
        sa.Column("enemies_flashed_per_round_in_a_match", sa.Float(), nullable=True),
        sa.Column("flash_success_rate_per_match", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_stats")
    op.create_table(
        "matches_info",
        sa.Column("faceit_match_id", sa.VARCHAR(), nullable=False),
        sa.Column("rounds", sa.BLOB(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_match_association",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("player_id", sa.INTEGER(), nullable=False),
        sa.Column("match_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "match_id", name="index_unique_player_match"),
    )
    # ### end Alembic commands ###
