"""replace_bool_roles_with_enum

Revision ID: 7988c2f590db
Revises: fa9c58e0a7eb
Create Date: 2025-03-26 18:34:19.947546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7988c2f590db"
down_revision: Union[str, None] = "fa9c58e0a7eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", "SUPER_ADMIN", name="userrole"),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
    )
    op.drop_column("users", "is_admin")
    op.drop_column("users", "is_super_admin")
    op.drop_column("users", "is_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_user", sa.BOOLEAN(), server_default=sa.text("(true)"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_super_admin",
            sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_admin", sa.BOOLEAN(), server_default=sa.text("(false)"), nullable=False
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
